version: "3.7"
services:
  env:
    build: .
    ports:
      - "4000:80"
    entrypoint: ["/bin/sh"]
  rel:
    build: .
    ports:
      - "4000:80"
  dev:
    build: .
    ports:
      - "4000:80"
    volumes:
      - ./src:/app/src
